name: CI

on: [push, pull_request]

jobs:
  run-linters:
    name: Check markdown
    runs-on: ubuntu-24.04
    container: node:16-alpine
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: ./node_modules/.bin/markdownlint-cli2 **/*.md
